# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=200, null=True, verbose_name='openid')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
