# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomo', '0002_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='vote',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='header_image', verbose_name='副图'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='header_image', verbose_name='头图'),
        ),
    ]
