# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lomo.models


class Migration(migrations.Migration):

    dependencies = [
        ('lomo', '0003_auto_20171016_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to=lomo.models.image_file_path, verbose_name='图片')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='choice',
            name='belong_to_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lomo.Vote', verbose_name='属于'),
        ),
    ]
