# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomo', '0005_vote_thumb_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='editor_say',
            field=models.CharField(blank=True, max_length=200, verbose_name='小编说'),
        ),
    ]
