# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomo', '0006_vote_editor_say'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='single_choice',
            field=models.IntegerField(blank=True, choices=[(1, '是'), (0, '否')], default=0, verbose_name='可否多选'),
        ),
    ]
