# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lomo', '0007_vote_single_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='belong_to_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lomo.Vote', verbose_name='属于'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='belong_to_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lomo.Choice', verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='belong_to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lomo.WxUser', verbose_name='用户'),
        ),
    ]
