# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lomo.models


class Migration(migrations.Migration):

    dependencies = [
        ('lomo', '0008_auto_20171021_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(blank=True, verbose_name='文章内容')),
                ('header_image', models.ImageField(blank=True, upload_to=lomo.models.image_file_path, verbose_name='封面图')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('belong_to_vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='lomo.Vote', verbose_name='属于')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='wxuser',
            options={'ordering': ['-created_date']},
        ),
    ]
