# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import lomo.models


class Migration(migrations.Migration):

    dependencies = [
        ('lomo', '0009_auto_20171024_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_image',
            field=models.ImageField(blank=True, upload_to=lomo.models.article_image_path, verbose_name='简介图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, upload_to=lomo.models.article_image_path, verbose_name='封面图'),
        ),
    ]
