# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import lomo.models


class Migration(migrations.Migration):

    dependencies = [
        ('lomo', '0010_auto_20171026_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, upload_to=lomo.models.article_image_path, verbose_name='全屏图'),
        ),
    ]
